services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dohssheba-backend
    restart: always
    network_mode: host
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    env_file:
      - ./backend/.env
    environment:
      - PORT=5008
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:123456@127.0.0.1:5432/dohsheba_db?schema=public

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://shop.dohsedu.com/api/v1
    container_name: dohssheba-frontend
    restart: always
    ports:
      - "3008:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=https://shop.dohsedu.com/api/v1
      - INTERNAL_API_URL=http://host.docker.internal:5008/api/v1
    depends_on:
      - backend
    networks:
      - dohssheba-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dohssheba-network:
    driver: bridge
